services:
  weather-srv:
    build: .
    env_file: ../.env
    command: uvicorn app:app --host 0.0.0.0
    networks:
      - database_postgres-net
      - app-backend_app-net

networks: 
  app-backend_app-net:
    external: true
  database_postgres-net:
    external: true
