services:
  backend:
    build: .
    env_file: ../.env
    ports:
      - 8888:8000
    command: uvicorn app:app --host 0.0.0.0
    networks:
      - app-net
      - database_postgres-net

networks: 
  app-net:
    driver: bridge
  database_postgres-net:
    external: true
